name: gradio_sample_app_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - gradio
    - langchain
    - langchain-core
    - langchain-community
    - langchain-ollama
